[alembic]
# 1. Indicamos la carpeta física donde viven tus migraciones
script_location = alembic

# 2. Permitimos que Python busque módulos en la raíz
prepend_sys_path = .
version_path_separator = os

# 3. Marcador de posición (tu env.py dinámico se encargará de cambiarlo en Render)
sqlalchemy.url = postgresql://placeholder